
'use client';

import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Loader2, Save, X, Building2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { Proveedor } from '@/types';
import { TIPO_PROVEEDOR_OPCIONES } from '@/types';

import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { useLoadingStore } from '@/hooks/use-loading-store';
import { MultiSelect } from '@/components/ui/multi-select';

export const proveedorSchema = z.object({
  id: z.string(),
  cif: z.string().min(1, "El CIF es obligatorio."),
  IdERP: z.string().optional(),
  nombreEmpresa: z.string().min(1, "El nombre fiscal es obligatorio."),
  nombreComercial: z.string().min(1, "El nombre comercial es obligatorio."),
  direccionFacturacion: z.string().min(1, "La dirección es obligatoria."),
  codigoPostal: z.string().min(1, "El código postal es obligatorio."),
  ciudad: z.string().min(1, "La ciudad es obligatoria."),
  provincia: z.string().min(1, "La provincia es obligatoria."),
  pais: z.string().min(1, "El país es obligatorio."),
  emailContacto: z.string().email("Debe ser un email válido."),
  telefonoContacto: z.string(),
  iban: z.string().optional(),
  formaDePagoHabitual: z.string().optional(),
  tipos: z.array(z.string()).min(1, "Debe seleccionar al menos un tipo de servicio."),
});

export type ProveedorFormValues = z.infer<typeof proveedorSchema>;

export default function NuevoProveedorPage() {
  const router = useRouter();
  const { isLoading, setIsLoading } = useLoadingStore();
  const { toast } = useToast();

  const form = useForm<ProveedorFormValues>({
    resolver: zodResolver(proveedorSchema),
    defaultValues: {
      id: Date.now().toString(),
      tipos: [],
      pais: 'España',
      cif: '',
      IdERP: '',
      nombreEmpresa: '',
      nombreComercial: '',
      direccionFacturacion: '',
      codigoPostal: '',
      ciudad: '',
      provincia: '',
      emailContacto: '',
      telefonoContacto: '',
      iban: '',
      formaDePagoHabitual: '',
    },
  });

  async function onSubmit(data: ProveedorFormValues) {
    setIsLoading(true);

    try {
      // Check for existing provider with same CIF in Supabase
      // We can't easily check all without fetching, but we can rely on the store or just check DB
      // For now, let's trust the DB constraint or check via query if needed.
      // But since we are migrating, let's just insert.

      // Construct the JSONB object for 'contacto'
      // We exclude 'id' (generated by DB) and 'nombreComercial' (mapped to 'nombre')
      const { id, nombreComercial, ...rest } = data;

      const contactoData = {
        ...rest,
        nombreEmpresa: data.nombreEmpresa, // Ensure these are included
        cif: data.cif,
        // Add other fields that are part of Proveedor but not in the top-level columns
      };

      const { error } = await supabase
        .from('proveedores')
        .insert({
          nombre: nombreComercial,
          contacto: contactoData
        });

      if (error) throw error;

      toast({ description: 'Nuevo proveedor añadido correctamente.' });

      // Refresh the store to get the new data
      // We need to import useDataStore. Since we are in a component, we can use the hook, 
      // but refreshData is on the store.
      // We can just call window.location.reload() or let the store handle it.
      // Better to trigger a refresh.
      // For now, let's just redirect. The list page might need to trigger a refresh.

      router.push('/bd/proveedores');
    } catch (error: any) {
      console.error('Error creating provider:', error);
      toast({ variant: 'destructive', title: 'Error', description: 'Error al guardar el proveedor: ' + error.message });
    } finally {
      setIsLoading(false);
    }
  }

  const tiposOptions = TIPO_PROVEEDOR_OPCIONES.map(t => ({ label: t, value: t }));

  return (
    <main>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <Building2 className="h-8 w-8" />
              <h1 className="text-3xl font-headline font-bold">Nuevo Proveedor</h1>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" type="button" onClick={() => router.push('/bd/proveedores')}> <X className="mr-2" /> Cancelar</Button>
              <Button type="submit" disabled={isLoading}>
                {isLoading ? <Loader2 className="animate-spin" /> : <Save />}
                <span className="ml-2">Guardar Proveedor</span>
              </Button>
            </div>
          </div>

          <Card>
            <CardHeader><CardTitle className="text-lg">Información Fiscal y de Contacto</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <FormField control={form.control} name="nombreEmpresa" render={({ field }) => (
                  <FormItem><FormLabel>Nombre Fiscal</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="nombreComercial" render={({ field }) => (
                  <FormItem><FormLabel>Nombre Comercial</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="cif" render={({ field }) => (
                  <FormItem><FormLabel>CIF/NIF</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
              </div>
              <FormField control={form.control} name="direccionFacturacion" render={({ field }) => (
                <FormItem><FormLabel>Dirección Fiscal</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
              )} />
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <FormField control={form.control} name="codigoPostal" render={({ field }) => (
                  <FormItem><FormLabel>Cód. Postal</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="ciudad" render={({ field }) => (
                  <FormItem><FormLabel>Ciudad</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="provincia" render={({ field }) => (
                  <FormItem><FormLabel>Provincia</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="pais" render={({ field }) => (
                  <FormItem><FormLabel>País</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField control={form.control} name="emailContacto" render={({ field }) => (
                  <FormItem><FormLabel>Email Contacto</FormLabel><FormControl><Input type="email" {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="telefonoContacto" render={({ field }) => (
                  <FormItem><FormLabel>Teléfono Contacto</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Información de Servicio y Facturación</CardTitle>
              <CardDescription>Selecciona los tipos de servicio que ofrece este proveedor para que aparezca en los módulos correspondientes.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <FormField control={form.control} name="tipos" render={({ field }) => (
                <FormItem>
                  <FormLabel>Tipos de Servicio</FormLabel>
                  <MultiSelect
                    options={tiposOptions}
                    selected={field.value}
                    onChange={field.onChange}
                    placeholder="Seleccionar tipos..."
                  />
                  <FormMessage />
                </FormItem>
              )} />
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <FormField control={form.control} name="IdERP" render={({ field }) => (
                  <FormItem><FormLabel>ID en ERP</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="iban" render={({ field }) => (
                  <FormItem><FormLabel>IBAN</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
                <FormField control={form.control} name="formaDePagoHabitual" render={({ field }) => (
                  <FormItem><FormLabel>Forma de Pago Habitual</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>
                )} />
              </div>
            </CardContent>
          </Card>
        </form>
      </Form>
    </main>
  );
}
